### ISSUE TITLE
Registration Validation

### ISSUE THREAD

**Issue by UnicornChance** [defenseunicorns/uds-identity-config#126]
### Description
We need to do the custom RegistrationValidation registration-validation-action  for SAML registration flows too.

In  RegistrationValidation registration-validation-action we at a miniumum should validate all user.attributes.* in the form data (including unexpected attributes), but could validate all formdata fields

### Completion
**When completed have @bburky review changes**

### Severity/Priority
High Priority

**Comment by bburky** [comment]
> We need to do the custom RegistrationValidation registration-validation-action for SAML registration flows too.

I think this can be done by setting "First login flow override" to "UDS Registration". But we should actually treat SAML login like x509 login too: password should be optional. And we should autofill the registration form from the SAML data.

**Comment by bburky** [comment]
> In RegistrationValidation registration-validation-action we at a miniumum should validate all user.attributes.* in the form data (including unexpected attributes), but could validate all formdata fields

We do check some fields, but we should actually validate all `user.attributes.*` fields at a minimum. We could validate the entire formdata (this would be best), but new fields may appear during keycloak upgrades and cause unexpected failures. If we add a good unit/e2e test, this maybe would be ok?

https://github.com/defenseunicorns/uds-identity-config/blob/af57ca9e432ddfa18859cd4aa5229fcaa840259e/src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/RegistrationValidation.java#L122

**Comment by UnicornChance** [comment]
> > We need to do the custom RegistrationValidation registration-validation-action for SAML registration flows too.
> 
> _Maybe_ this can be done by setting "First login flow override" to "UDS Registration". (I'm not quite sure if this is correct, it should only happen on the first login ever, not every time) You may need to make a custom flow for this.
> 
> But during the registration form, we should actually treat SAML login like x509 login too: password should be optional.
> 
> And we should autofill the registration form from the SAML data. (they actually should _not_ be able to reconfigure anything SAML-provided, and we should make sure every new SAML login updates all the SAML-provided values)

Looking at this a bit more, if im understanding this correctly we want the ability to validate the user attributes being created by saml IDP. In addition to that we want to optionally enable a user to create a password for their account. 

Initial thought: this auto fill capability is something I'll have to implement on the registration form somehow. 

Am i understanding this correctly before i get too far down a rabbit hole?

**Comment by bburky** [comment]
The main thing is:
Ensure all attributes have `RegistrationValidation.validate()` applied to them 
https://github.com/defenseunicorns/uds-identity-config/blob/v0.5.0/src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/RegistrationValidation.java#L93

Honestly, we could perhaps skip the registration form for now. Generally we don't want the user able to edit the attributes provided by SAML (email should never be editable by user for example). But currently the validation considers affiliation/rank/organization to be required attributes, so I was thinking a form. But maybe just actually make those fields configurable to disable validating them. Or tell people they need to pass them in via SAML too.

A form could make sense at some point, but skipping it would probably make the scope of this issue smaller

**Comment by UnicornChance** [comment]
Basic username/password form validation is completed, however still want to implement validation on saml registration.
