### ISSUE TITLE
Set realm settings as environment variables

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-identity-config#32]
### Is your feature request related to a problem? Please describe.

Currently if I want to change certain realm settings I would have to rebuild the realm or change it in the admin console at deploy time.

It would be ideal to have some realm items configurable at deploy time (currently `x509-cert-auth.ocsp-fail-open` feels like a good one to change).

### Describe the solution you'd like

Keycloak allows environment variables to be used in a realm import, see https://www.keycloak.org/server/importExport#_importing_a_realm_during_startup . This seems like an easy way to expose this as configurable (would need to be added to the keycloak helm chart to fully expose).

### Describe alternatives you've considered

End user can rebuild image with their custom realm.

### Additional context

We already use environment variables to handle the domain.

**Comment by UnicornChance** [comment]
Potential value to look at is OTP.
